--- 
author: "Equipo de Soluciones Hospedadas"
category_dir: blog/categories
code_dir: downloads/code
date_format: "%d/%m/%Y"
default_asides: 
  - asides/recent_posts.html
  - asides/github.html
  - asides/delicious.html
  - asides/pinboard.html
  - asides/googleplus.html
delicious_count: 3
delicious_user: ~
description: ~
destination: public
disqus_short_name: ~
disqus_show_comment_count: false
email: ~
excerpt_link: "Continuar leyendo →"
facebook_like: false
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true
github_user: ~
google_analytics_tracking_id: ~
google_plus_one: false
google_plus_one_size: medium
googleplus_hidden: false
googleplus_user: ~
markdown: rdiscount
paginate: 10
pagination_dir: blog
permalink: "/blog/:year/:month/:day/:title/"
pinboard_count: 3
pinboard_user: ~
plugins: plugins
pygments: false
recent_posts: 5
root: /
simple_search: "http://google.com/search"
source: source
subscribe_email: ~
subscribe_rss: /atom.xml
subtitle: "Desde las nubes"
title: "Blog de Soluciones hospedadas"
titlecase: true
twitter_follow_button: true
twitter_show_follower_count: false
twitter_show_replies: false
twitter_tweet_button: true
twitter_tweet_count: 4
twitter_user: shcloudservices
url: http://shcloudservices.github.com

